### PR TITLE
Convert base64 text to images/gifs

### LINKED ISSUE #951: [BUG] App freezes when opening the dm screen
**Describe the bug**
App freezes when opening the dm screen

**To Reproduce**
1. Open the app
2. Press the dm screen icon
3. The app freezes

**Expected behavior**

**Video and Screenshots**

**Device (please complete the following information):**

**Bounty (in Bitcoin sats) offered for a solution**

### PR DESCRIPTION
**Pull request by greenart7c3**
fixes #951

### CODE REVIEW

**Comment by greenart7c3** [comment]
It still freezes the app if i press the show more button. Should I try to change the text note to make it convert the base64 to a image?

**Comment by vitorpamplona** [comment]
I think we will have to :(

File: amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt [hunk 1]
```diff
@@ -433,6 +447,43 @@ private fun RenderWordWithPreview(
...
+fun ImageFromBase64(base64String: String) {
+    val context = LocalContext.current
+
+    var base64String2 = base64String.removePrefix("data:image/jpeg;base64,")
+    RichTextParser.imageExtensions.forEach {
+        base64String2 = base64String2.removePrefix("data:image/$it;base64,")
+    }
+
+    val imageBytes = runCatching { Base64.decode(base64String2, Base64.DEFAULT) }.getOrNull()
+
```
Comment (vitorpamplona) [inline amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt:464]: You can also use the Base64 Requester which I think does the decoding in an IO thread. 
```kt
            val context = LocalContext.current
            val base64Painter =
                rememberAsyncImagePainter(
                    model = Base64Requester.imageRequest(context, model),
                )

            Image(
                painter = base64Painter,
                contentDescription = contentDescription,
                modifier = modifier,
                alignment = alignment,
                contentScale = contentScale,
                colorFilter = colorFilter,
            )
```

File: commons/src/main/java/com/vitorpamplona/amethyst/commons/richtext/RichTextParser.kt [hunk 2]
```diff
@@ -112,20 +127,23 @@ class RichTextParser {
     ): RichTextViewerState {
         val urlSet = parseValidUrls(content)
 
+        val base64Images = parseBase64Images(content)
```
Comment (vitorpamplona) [inline commons/src/main/java/com/vitorpamplona/amethyst/commons/richtext/RichTextParser.kt:130]: This might be really slow. I would run it on the wordIdentifier. Check if each word starts with `data:image` and if so go for the full parse. It avoids running the entire regex when no base64 images can be found.

File: amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt (hunk 1 above)
Comment (greenart7c3) [reply amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt]: Using this makes base64 gifs not work

**Review by KotlinGeekDev — COMMENTED** [review]
Please @greenart7c3 can you try this solution?(It's a slight modification of @vitorpamplona 's suggestion. Needs Coil's gif library extension, see [here](https://coil-kt.github.io/coil/gifs/).
Edit: moved LocalContext call to the top, for correctness.
```kotlin
val context = LocalContext.current
val gifImageLoader = ImageLoader.Builder(context)
    .components {
        if (SDK_INT >= 28) {
            add(ImageDecoderDecoder.Factory())
        } else {
            add(GifDecoder.Factory())
        }
    }
    .build()

val base64Painter =
    rememberAsyncImagePainter(
      model = Base64Requester.imageRequest(context, model),
      imageLoader = gifImageLoader
    )

Image(
    painter = base64Painter,
    contentDescription = contentDescription,
    modifier = modifier,
    alignment = alignment,
    contentScale = contentScale,
    colorFilter = colorFilter,
)   

```

File: amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt (hunk 1 above)
Comment (KotlinGeekDev) [reply amethyst/src/main/java/com/vitorpamplona/amethyst/ui/components/RichTextViewer.kt:464]: Please @greenart7c3 can you try this solution?(It's a slight modification of @vitorpamplona 's suggestion. Needs Coil's gif library extension, see [here](https://coil-kt.github.io/coil/gifs/).
```kotlin
val gifImageLoader = ImageLoader.Builder(context)
    .components {
        if (SDK_INT >= 28) {
            add(ImageDecoderDecoder.Factory())
        } else {
            add(GifDecoder.Factory())
        }
    }
    .build()

val context = LocalContext.current
val base64Painter =
    rememberAsyncImagePainter(
      model = Base64Requester.imageRequest(context, model),
      imageLoader = gifImageLoader
    )

Image(
    painter = base64Painter,
    contentDescription = contentDescription,
    modifier = modifier,
    alignment = alignment,
    contentScale = contentScale,
    colorFilter = colorFilter,
)   

```

**Comment by greenart7c3** [comment]
Thanks, I'll test this tomorrow morning

**Comment by greenart7c3** [comment]
Gifs doesn't animate when I use this solution

**Comment by KotlinGeekDev** [comment]
> Gifs doesn't animate when I use this solution

Thanks for the feedback. I guess the problem is at the level of Coil then.

**Comment by davotoula** [comment]
Trying this pull request. How is this functionality invoked from the app please?

**Comment by davotoula** [comment]
Very slow scrolling of home feed on first try. Is this a known issue or just cache priming?

**Comment by greenart7c3** [comment]
I'll look at this later. Have you tried creating a release build to see if it's slow too?

**Comment by davotoula** [comment]
It was a debug build... And trying other branches with a debug build it's similarly slow.

So I suspect it's the debug build rather than your PR 👍

**Comment by vitorpamplona** [comment]
Yeah, debug will always be extremely slow due to the added tracking points for debug. 

Use the "benchmark" build variant to see real speeds.

**Comment by davotoula** [comment]
Good point, thanks!
